import { Book, Review, UserBook } from '@/types';

export const mockBooks: Book[] = [
  {
    id: '1',
    isbn: '9784873119045',
    title: 'プログラミング TypeScript',
    author: 'Boris Cherny',
    language: 'TypeScript',
    categories: ['フロントエンド', 'JavaScript'],
    img_url: 'https://images.pexels.com/photos/3747279/pexels-photo-3747279.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 3,
    description: 'TypeScriptの基礎から高度な型の扱いまで、実践的なサンプルコードとともに解説。JavaScriptプログラマーが安全で拡張性の高いコードを書くための必読書。',
  },
  {
    id: '2',
    isbn: '9784873119700',
    title: 'JavaScript 第7版',
    author: 'David Flanagan',
    language: 'JavaScript',
    categories: ['フロントエンド', 'JavaScript'],
    img_url: 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 2,
    description: 'JavaScriptの基礎から応用まで幅広くカバーしたリファレンス。Node.js、ブラウザAPI、非同期プログラミングなど幅広いトピックを解説。',
  },
  {
    id: '3',
    isbn: '9784873119380',
    title: 'React ハンズオン ラーニング',
    author: 'Alex Banks, Eve Porcello',
    language: 'JavaScript',
    categories: ['フロントエンド', 'React'],
    img_url: 'https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 2,
    description: 'Reactの基本概念からRedux、React Hooksまで、実践的なプロジェクトを通して学ぶ入門書。初心者から中級者まで幅広く対応。',
  },
  {
    id: '4',
    isbn: '9784873117836',
    title: 'Python データサイエンスハンドブック',
    author: 'Jake VanderPlas',
    language: 'Python',
    categories: ['バックエンド', 'データサイエンス'],
    img_url: 'https://images.pexels.com/photos/4115236/pexels-photo-4115236.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 4,
    description: 'Python のデータサイエンスライブラリ（NumPy、pandas、Matplotlib、scikit-learn）を活用したデータ分析と可視化の実践ガイド。',
  },
  {
    id: '5',
    isbn: '9784873118369',
    title: 'Go言語による並行処理',
    author: 'Katherine Cox-Buday',
    language: 'Go',
    categories: ['バックエンド'],
    img_url: 'https://images.pexels.com/photos/11035524/pexels-photo-11035524.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 4,
    description: 'Goの並行処理機能（ゴルーチン、チャネル、セレクト）を活用した効率的なプログラミング手法を解説。並行処理のパターンとアンチパターンを学ぶ。',
  },
  {
    id: '6',
    isbn: '9784873118932',
    title: 'Kubernetes完全ガイド',
    author: '青山真也',
    language: 'その他',
    categories: ['インフラ', 'DevOps'],
    img_url: 'https://images.pexels.com/photos/11035501/pexels-photo-11035501.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 5,
    description: 'コンテナオーケストレーションツールKubernetesの設計思想、アーキテクチャ、運用手法までを網羅したガイド。本番環境での活用法も解説。',
  },
  {
    id: '7',
    isbn: '9784873118864',
    title: 'Java本格入門',
    author: '谷本心',
    language: 'Java',
    categories: ['バックエンド'],
    img_url: 'https://images.pexels.com/photos/11035390/pexels-photo-11035390.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 1,
    description: 'Javaプログラミングの基礎からオブジェクト指向、実践的なアプリケーション開発まで段階的に学べる入門書。初心者でも理解しやすい解説。',
  },
  {
    id: '8',
    isbn: '9784873119373',
    title: 'Rustプログラミング入門',
    author: 'Jim Blandy, Jason Orendorff, Leonora F.S. Tindall',
    language: 'Rust',
    categories: ['バックエンド', 'システムプログラミング'],
    img_url: 'https://images.pexels.com/photos/4545156/pexels-photo-4545156.jpeg?auto=compress&cs=tinysrgb&w=800',
    avg_difficulty: 5,
    description: 'Rustの特徴である所有権とボローチェックを理解し、安全で高速なプログラムを書く方法を学ぶ入門書。コンカレンシーやFFIなどの高度なトピックも解説。',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    user_id: 'user1',
    user_name: 'プログラミング好き',
    book_id: '1',
    difficulty: 4,
    experience_years: 2,
    comment: 'TypeScriptの型システムの理解が深まりました。特に Union Types や Intersection Types の解説が分かりやすかったです。中級から上級者向けだと思います。',
    created_at: '2023-10-15T08:30:00Z',
  },
  {
    id: '2',
    user_id: 'user2',
    user_name: 'フロントエンジニア',
    book_id: '1',
    difficulty: 3,
    experience_years: 4,
    comment: '業務で使うTypeScriptの理解が格段に向上しました。型定義のセクションは特に参考になりました。エラーメッセージの読み方も学べて良かったです。',
    created_at: '2023-09-22T14:45:00Z',
  },
  {
    id: '3',
    user_id: 'user3',
    user_name: 'バックエンド開発者',
    book_id: '1',
    difficulty: 5,
    experience_years: 1,
    comment: '初心者にはややハードルが高いかも。TypeScriptの経験が少ない状態で読むと難しく感じました。もう少しJavaScriptの基礎を固めてから読み直そうと思います。',
    created_at: '2023-11-05T10:15:00Z',
  },
  {
    id: '4',
    user_id: 'user4',
    user_name: 'アーキテクト',
    book_id: '1',
    difficulty: 3,
    experience_years: 7,
    comment: '高度な型の活用方法が参考になりました。特にジェネリクスやcondition typesの実践的な例が多く、実務での型設計の参考になります。',
    created_at: '2024-01-10T16:20:00Z',
  },
];

export const mockUserBooks: UserBook[] = [
  {
    id: '1',
    user_id: 'currentUser',
    book: mockBooks[0],
    status: 'reading',
    progress: 60,
    added_at: '2024-01-15T10:30:00Z',
    finished_at: null,
  },
  {
    id: '2',
    user_id: 'currentUser',
    book: mockBooks[1],
    status: 'done',
    progress: 100,
    added_at: '2023-12-05T09:15:00Z',
    finished_at: '2023-12-20T18:45:00Z',
  },
  {
    id: '3',
    user_id: 'currentUser',
    book: mockBooks[2],
    status: 'unread',
    progress: 0,
    added_at: '2024-02-01T14:10:00Z',
    finished_at: null,
  },
  {
    id: '4',
    user_id: 'currentUser',
    book: mockBooks[3],
    status: 'reading',
    progress: 25,
    added_at: '2024-01-28T11:20:00Z',
    finished_at: null,
  },
];